# Generated by Django 2.1.7 on 2020-10-23 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201023_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 23, 15, 23, 44, 403137)),
        ),
    ]
